os: linux
dist: trusty
language: node_js
node_js:
  - 10
cache: npm
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - npm run test:coverage:upload
deploy:
  provider: script
  cleanup: true
  script: npx semantic-release
